baseURL = "https://nrguam.netlify.app/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[[menu.footer]]
name = "Featured"
url = "https://search.idxhome.com/featured/162504"
weight = 5
[[menu.footer]]
name = "Sell"
url = "/pages/sell"
weight = 3
[[menu.footer]]
name = "Buy"
url = "/pages/buy"
weight = 2
[[menu.footer]]
name = "Lease"
url = "/pages/lease"
weight = 4
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Lease"
url = "/pages/lease"
weight = 4
[[menu.main]]
name = "Featured"
url = "https://search.idxhome.com/featured/162504"
weight = 5
[[menu.main]]
name = "Buy"
url = "https://search.idxhome.com/homesearch/162504"
weight = 2
[[menu.main]]
name = "Sell"
url = "pages/sell"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
